### ISSUE TITLE
Error when setting up for Basejumps

### ISSUE THREAD

**Issue by su6a12** [clnhll/guidetobasejumps#2]
This is the error I'm getting while trying to set up my environment on cloud9 for basejumps.  I've encountered this multiple times and I'm not sure where I've gone wrong.

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at destinationPath (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:80:13)
    at Object.relativeRequire (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:88:8)
    at Generator.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/script-base.js:37:25)
    at eval (eval at template (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:8:11)
    at underscore (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at Generator.actions.engine (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:216:32)
    at Generator.template (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:191:19)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:159:14
    at Array.forEach (native)
    at Object.processDirectory (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:129:9)

**Comment by m66n** [comment]
Check out [this issue for generator-angular-fullstack](https://github.com/DaftMonk/generator-angular-fullstack/issues/1197). Cloud 9 is using nodejs v0.10, but the generator expects v0.12. I worked around it [as detailed here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2722#issuecomment-136236921).

**Comment by su6a12** [comment]
Thanks @m66n
